server:
  port: 8080
  servlet:
    context-path: /shopapp

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shopapp"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-email-password
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true

jwt:
  signerKey: "05ym9Z5YaEWpqOa5NFWC90ulkXxlI05uOQJgY3FxBDFkhPl+XJSb0kHkK9mFSgXT"
  valid-duration: 3600 #in second
  refreshable-duration: 360000 # in seconds
